version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: .
    ports:
      - "7000:7000"
    command: /opt/venv/bin/gunicorn -w 1 -b 0.0.0.0:7000 youtube_dl_web.wsgi:app